### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by rugk** [morevnaproject/opentoonz#11]
It would be great to get a flatpak version, which can be installed on all major Linux distros.

**Comment by morevnaproject** [comment]
We provide Appimage package, which can be installed on all major Linux distros. Please submit the request about FlatPack to official issue tracker of OpenToonz.

**Comment by rugk** [comment]
Oh this is not the official version? Is this a fork?

**Comment by morevnaproject** [comment]
No, we are not fork. The features developed by our team are submitted to official OpenToonz version and (eventually) getting merged.

We also providing early testing builds with our changes to allow people do early testing of new features.
