### ISSUE TITLE
Release build (v1.2.0.3-morevna) not starting in fedora 28

### ISSUE THREAD

**Issue by legocef01** [morevnaproject/opentoonz#16]
I can't start morevna opentoonz 1.2.0.3 in fedora 28. It crashes.
That's what I have in terminal when starting morevna-opentoonz appimage : 

plugin search directory:/home/legocef/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/legocef/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
plugin search directory:/home/legocef/.config/OpenToonz/stuff/plugins
walkDictionary: /home/legocef/.config/OpenToonz/stuff/plugins [dry]
PaletteViewerGUI::PaletteTabBar(0x32b5130, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x32b5130, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
DVGui::TabBar(0x3927410, name="StyleEditorTabBar")  does not have a property named  "BottomAboveLineColor"
DVGui::TabBar(0x3927410, name="StyleEditorTabBar")  does not have a property named  "BottomBelowLineColor"
DVGui::TabBar(0x2af0b30, name="StyleEditorTabBar")  does not have a property named  "BottomAboveLineColor"
DVGui::TabBar(0x2af0b30, name="StyleEditorTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x3929740, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x3929740, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x463c0a0, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x463c0a0, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x2acbf60, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x2acbf60, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
DVGui::TabBar(0x465e6b0, name="StyleEditorTabBar")  does not have a property named  "BottomAboveLineColor"
DVGui::TabBar(0x465e6b0, name="StyleEditorTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x4903fc0, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x4903fc0, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function sk_num
/tmp/.mount_06Bb5w/usr/bin/launch-opentoonz.sh: line 82: 15971 Segmentation fault      (core dumped) ./opentoonz "$@"

**Comment by legocef01** [comment]
Sorry, 
False alarm. 
I retried today, all thing if fine. Especially audio scubling.
Thank you very much.

**Comment by morevnaproject** [comment]
Glad to hear that! ^__^
