### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by hellocatfood** [morevnaproject/opentoonz#17]
### Issue Summary
When starting the Opentoonz 1.2.0.3 appimage I get the following terminal output:

```
./OpenToonz-1.2.0.3-morevna-18.06.17-linux64-b8b54.appimage 
update stuff
./../bin/OpenToonz_1.2: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers
```
### System Information
* **OpenToonz Version**: 1.2.0.3 appimage
* **Operating System**: Ubuntu 18.10
* **Graphics Card**: Intel

**Comment by hellocatfood** [comment]
If I run the following from the terminal then the program starts successfully:

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 ./OpenToonz-1.2.0.3-morevna-18.06.17-linux64-b8b54.appimage 
```

However, this is inconvenient to do it each time

**Comment by edukaded** [comment]
I've posted a guide to make it more convenient over here...
https://github.com/morevnaproject/opentoonz/issues/29
