### ISSUE TITLE
Release v1.3.0-morevna executable name

### ISSUE THREAD

**Issue by manongjohn** [morevnaproject/opentoonz#20]
### Issue Summary
Downloaded the v1.3.0-morevena 64-bit Windows installer.  After installation, the shortcut does not work because it cannot find OpenToonz_1.3.exe.  There is only a OpenToonz_1.2.exe in the bin folder.

The portable version also contains the OpenToonz_1.2.exe. The opentoonz.bat script uses OpenToonz_1.2.exe.

This impacts both 32-bit and 64-bit Windows installers.  Not sure how this will impact macOS and Linux builds.

The official OT 1.3 did away with version numbers in executable and stuff folder names.  Any intention of following suite or maybe instead of version number, replace with "morevna"?

**Comment by morevnaproject** [comment]
Thank you for reporting! Made a fix, rebuilding packages now... ^__^

**Comment by morevnaproject** [comment]
> The official OT 1.3 did away with version numbers in executable and stuff folder names. Any intention of following suite or maybe instead of version number, replace with "morevna"?

We will follow the same practice in the next release.

**Comment by morevnaproject** [comment]
Fixed now. Updated packages are available here - https://github.com/morevnaproject/opentoonz/releases/tag/v1.3.0-morevna
