### ISSUE TITLE
Release version 1.3.1

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/opentoonz#22]
- [x] Rebase "morevna" branch to version "1.3.0" of official OpenToonz.
- [x] Send PR with Assistants feature to official OpenToonz repository
- [x] Revert this commit in"morevna-builds" - https://github.com/morevnaproject/morevna-builds/commit/98489490fa72cd66f1687f8fc841214a7471ed59

**Comment by turtletooth** [comment]
Any news on this?  Looking forward to this!

**Comment by morevnaproject** [comment]
@turtletooth Sorry, didn't had time to work on it yet. BTW, did you managed to include Assistants into latest OTX? ^__^

**Comment by turtletooth** [comment]
No I didn't.  I tried, but I don't understand enough of what @blackwarthog did in this to take care of the merge conflicts.
