### ISSUE TITLE
Cannot open Any version on windows

### ISSUE THREAD

**Issue by ShadowTheReal** [morevnaproject/opentoonz#23]
### Issue Summary
if i try to open any version of opentoonz Morevna edition, it starts and once it has loaded completely, it just closes.
tested this on two different windows machines:
1) Windows 10 32 bit
2) Windows 7 64 bit
both had the same issue

### Steps to Reproduce
just try it

### Expected Results
working opentoonz

### Actual Results
discribed above

### System Information
* **OpenToonz Version**: 
any version
* **Operating System**: 
Windows 10
Windows 7
* **CPU**: 
Windows 10: Intel Atom Z3735F
Windows 7: idk
* **Memory**: 
Windows 10: 2gb
Windows 7: 32gb
* **Graphics Card**: 
Windows 10: no working graphics card
Windows 7: i don't know, but it has one

**Comment by morevnaproject** [comment]
Please check this article - https://desk.zoho.com/portal/morevnaproject/kb/articles/opentoonz-installs-but-crashes-on-start

**Comment by ShadowTheReal** [comment]
Ok, thanks
