### ISSUE TITLE
Assistant set to ellipse causes crash

### ISSUE THREAD

**Issue by artisteacher** [morevnaproject/opentoonz#24]
### Issue Summary

Clicking in the viewer after setting an assistant level to ellipse causes an immediate crash.

### Steps to Reproduce

1. Open a new scene
2. Using the assistant tool, set the mode to ellipse
3. Click in the viewer = crash

On a related note, the assistant is really hard to see when it is not active. Thanks for a helpful new addition!
<img width="799" alt="Screen Shot 2019-03-17 at 11 53 51 PM" src="https://user-images.githubusercontent.com/21159116/54505806-fa0cf100-490f-11e9-97ea-2c1a050212cb.png">

### System Information
* **OpenToonz Version**: 1.3.0
* **Operating System**: macOS 10.14.3
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by blackwarthog** [comment]
Please try our latest version for MacOS:
https://dev.icystar.com/downloads/OpenToonz-1.3.1-morevna-19.07.03-osx64-b9805.dmg

**Comment by artisteacher** [comment]
That release still has the same issues.

**Comment by morevnaproject** [comment]
Should be fixed now. Can you please check this package?  - https://coolbug.org/downloads/morevna/builds/OpenToonz-1.3.1-morevna-2020.01.25-osx64-3c693.dmg

**Comment by artisteacher** [comment]
The crash is fixed! The lines of the assistant are still really hard to see on a high resolution screen, but that should probably be a separate issue.
