### ISSUE TITLE
MyPaint brushes not working on Toonz Raster level

### ISSUE THREAD

**Issue by tbrimbo** [morevnaproject/opentoonz#25]
This is a feature available on [OpenToonz V1.3](https://github.com/opentoonz/opentoonz/pull/2257)
### Steps to Reproduce

- Create a new Toonz Raster level.
- Select brush tool.
- Open Raster tab on Style Editor.
- Draw on the canvas.
The result is a blank trace of brush movement.

### System Information
* **OpenToonz Version**:  1.3.0
* **Operating System**:  Arch Linux

**Comment by morevnaproject** [comment]
The OpenToonz Morevna Edition 1.3.0 includes all features of official OpenToonz 1.2.1 + features developed by Morevna team.

The features of official OpenToonz 1.3 will be shipped with OpenToonz Morevna Edition 1.3.1.
See #22.

**Comment by tbrimbo** [comment]
Ok, thanks. I didn't know what "rebasing" involved and wanted to let you know.

**Comment by morevnaproject** [comment]
Hi! We have released version 1.4.0, should be solved now - https://morevnaproject.org/2020/03/01/opentoonz-morevna-edition-1-4-0-released/
