### ISSUE TITLE
Unable to Customize Command Bar

### ISSUE THREAD

**Issue by tbrimbo** [morevnaproject/opentoonz#26]
### Issue Summary
Unable to drag and drop "toolbar items" to "command bar". 

### Screenshot or Video Reference
![Screenshot from 2019-03-19 12-13-27](https://user-images.githubusercontent.com/11670357/54605140-7ef72800-4a40-11e9-9886-806ac1fef756.png)

### Steps to Reproduce
- Right click on the command bar and select "Customize Command Bar".
- Select the tool you want to drag and drop from right hand side to left hand side.
- Unable to drag it. It stops mouse functioning. Mouse cursor moves but we cannot use it anywhere on the screen (including other applications and OS panel) until we press Esc on keyboard.. 

### System Information
* **OpenToonz Version**:  1.3.0
* **Operating System**:  Arch Linux

**Comment by morevnaproject** [comment]
Does this happens in official OpenToonz?

**Comment by tbrimbo** [comment]
This function works on official V1.3. I believe your reply to my other issue answers the question. The issue should be resolved when you rebase it to the Official version 1.3.

**Comment by morevnaproject** [comment]
Hi! We have released version 1.4.0 - https://morevnaproject.org/2020/03/01/opentoonz-morevna-edition-1-4-0-released/
Should be fixed now.
