### ISSUE TITLE
The whole system crashes when I run opentoonz

### ISSUE THREAD

**Issue by Gilraiser** [morevnaproject/opentoonz#27]
### Issue Summary

The whole system crashes when I run opentoonz. This happens in the morevna version and the other version.

### Steps to Reproduce

The error occurs when I install the program through the appimage, flatpack or from the Archlinux user repositories.

### System Information
* **OpenToonz Version: 1.3.0 Morevna and Dwango.
* **Operating System: Archlinux 64x
* **CPU**: Amd athlon 5150 APU. 4 cores, 4 threads
* **Memory**: 12 GB 
* **Graphics Card**: Nvidia Gforce GT 610 

I hope the information is useful.
see you soon

**Comment by morevnaproject** [comment]
This issue affects official opentoonz as well, so please report it to official repository - https://github.com/opentoonz/opentoonz/issues
