### ISSUE TITLE
Plans for 1.4

### ISSUE THREAD

**Issue by WPFilmmaker** [morevnaproject/opentoonz#30]
I thought it would be helpful to open this ticket to track version 1.4 so you can release your version accordingly.

https://github.com/opentoonz/opentoonz/issues/2868

**Comment by morevnaproject** [comment]
Thanks for this! We plan to release 1.4 soon ^__^

**Comment by morevnaproject** [comment]
Hi! We have released version 1.4.0 - https://morevnaproject.org/2020/03/01/opentoonz-morevna-edition-1-4-0-released/
