### ISSUE TITLE
Undefined or empty TOONZROOT

### ISSUE THREAD

**Issue by manongjohn** [morevnaproject/opentoonz#33]
### Issue Summary
I am reporting this on behalf of at least 2 users who reported an error when launching 1.3.1 (32bit version) and 1.4.0 after downloading and installing it.

Reinstalling did not appear to fix the problem.

### Screenshot or Video Reference
![b7dd6c1-1](https://user-images.githubusercontent.com/19245851/75681659-080f6b00-5c62-11ea-908f-e2c57350c5d5.png)

### System Information
* **OpenToonz Version**:  Morevna Edition 1.3.1 and 1.4.0
* **Operating System**: Windows

**Comment by morevnaproject** [comment]
Hi! Thanks for reporting! Do they use Portable version or Installer?

**Comment by manongjohn** [comment]
The 1.3.1 user initially used the installer and had this problem. I had them download the portable version as well and said he still had the same problem.

I'm not sure what version the 1.4.0 user used.

I wonder if it is an issue on machines that have never had OT installed on it before.

**Comment by morevnaproject** [comment]
Okay, it looks like I know what's going on. I just managed to reproduce this issue by installing 32bit OpenToonz on 64bit Windows OS. What is architecture of his OS?

**Comment by morevnaproject** [comment]
Ah, wait. the problem is not in that. I have reproduced same issue with 64bit version of OpenTOonz installer. Working on fixing...

**Comment by morevnaproject** [comment]
@blackwarthog I have updated builder, pulled changes to server and started build to make installers updated.

**Comment by blackwarthog** [comment]
> @blackwarthog I have updated builder, pulled changes to server and started build to make installers updated.

your fix in not complete, we need to fix the uninstaller and look the launcher
also we need someone to do following tests on windows system:

1 - install to clear system (without OT installed, without any previous OT registry entries) and run
2 - uninstall, and check that OT registry keys removed, also check stuff directory (user data should be kept)
3 - install again and run
4 - uninstall again, and check that OT registry keys removed, and check stuff

5 - install version 1.2 morevna and run
6 - try to install last morevna, installer should to block the installation and suggest to uninstall previous version manually. check consistency of OT registry keys after this, and check stuff folder (must be unchanged)
7 - uninstall and check registry (don't clean it manually, casual user cannot do it) and check stuff
8 - install last morevna, check registry and run, check stuff after run (used data must be safe, but ui configs must be updated)
9 - uninstall and check registry and user data in stuff

10-14: repeat steps 5-9 with OpenToonz 1.2 original
15-19: repeat steps 5-9 with OpenToonz 1.4 original

20 - try to install and run win32 version
21 - try to install last morevna win64 with installed win32 version (installer must prevent in)
22 - try to install last morevna win32 with installed win64 version (installer must prevent in)

**Comment by morevnaproject** [comment]
> your fix in not complete, we need to fix the uninstaller

@blackwarthog I have fixed uninstall here - https://github.com/morevnaproject/morevna-builds/commit/9b37a2a2f14986d7ea835ee0aa8c0b9cf7683d6f

> and look the launcher

We do not use launcher in Windows version. ^__^

> also we need someone to do following tests on windows system:

I am just testing install/run/uninstall on clean system. ^__^

**Comment by morevnaproject** [comment]
@manongjohn I have updated packages - https://github.com/morevnaproject/opentoonz/releases/tag/v1.4.0-morevna

Should be fixed now.

**Comment by morevnaproject** [comment]
Is it okay to close this now?

**Comment by manongjohn** [comment]
I haven't heard back from the user recently, but we can assume it is fixed for now.

If it is still an issue, I'll reopen the ticket.

Thanks for fixing so quickly!
