### ISSUE TITLE
the main window is completely black on ubuntu 22.04

### ISSUE THREAD

**Issue by mzaulychny** [morevnaproject/opentoonz#48]
Hi,
 I have a problem when I start the program, the main window is all black everything works only the main window is black.

![Screenshot_20221008_223411](https://user-images.githubusercontent.com/23351834/194724582-64bbf798-f3a8-4306-98c6-7236f392fd1f.png)

**Comment by mzaulychny** [comment]
when I restarted my PC, it's go beck to normal.

**Comment by morevnaproject** [comment]
Great to hear! Thanks for the update
