### ISSUE TITLE
No Context Menu on Workspace.

### ISSUE THREAD

**Issue by ebarranco** [morevnaproject/opentoonz#5]
The right click of the pen in the graphics tablet does not brings up Context Menu on the workspace in all last versions of  morevna opentoonz. [I explain the problem here.](https://www.dropbox.com/s/2xd2u1cj5dstvnx/OpentoonzSecondaryMenu.mp4?dl=0)

**Comment by morevnaproject** [comment]
Hello Enrique! Thank you for reporting!
This is possibly related with opentoonz/opentoonz#1360, which we will try to rollback in the next release.

In any case, can I ask you to submit this issue to https://github.com/opentoonz/opentoonz/issues - it is possible  this affects Windows users of official version as well.

**Comment by coreyryanhanson** [comment]
I get the same issue with a wacom intuos pro running 1.2.02 on CentOs7.4. On the main canvas window where the drawing happens, it doesn't work but on other panels it seems to work fine.

**Comment by morevnaproject** [comment]
@coreyryanhanson Can I ask you to submit this issue to https://github.com/opentoonz/opentoonz/issues - it is possible this affects Windows users of official version as well.

**Comment by coreyryanhanson** [comment]
@morevnaproject I totally would, but don't have a means of testing the upstream version since dependency hell complicates building it manually on the distro I use. I get error messages saying that SuperLU is missing where both it and the devel package is already installed.

**Comment by ebarranco** [comment]
@morevnaproject done!

**Comment by morevnaproject** [comment]
https://github.com/opentoonz/opentoonz/issues/1790
