### ISSUE TITLE
Images won't go outside it's border

### ISSUE THREAD

**Issue by dryadtess** [morevnaproject/opentoonz#9]
When I try to move around an image that's pretty small, I can't see the image outside it's original placement on the stage. 
<img width="960" alt="2018-05-02 0" src="https://user-images.githubusercontent.com/38961317/40130599-2cdc9490-58fd-11e8-9674-23343d4e1bd2.png">
So I load in the image 
<img width="960" alt="2018-05-02 1" src="https://user-images.githubusercontent.com/38961317/40130609-3262c7c2-58fd-11e8-84db-1b4b2de4421a.png">
I select it
<img width="960" alt="2018-05-02 2" src="https://user-images.githubusercontent.com/38961317/40130616-36526afe-58fd-11e8-9280-cc20347dadf0.png">
I have the option to move it
<img width="960" alt="2018-05-02 3" src="https://user-images.githubusercontent.com/38961317/40130619-389832a8-58fd-11e8-882b-e6aa158fbc0d.png">
I move it somewhere else- oh, wait, I can't! It won't go outside the border it was loaded in!
<img width="960" alt="2018-05-02 4" src="https://user-images.githubusercontent.com/38961317/40130622-3a774f78-58fd-11e8-9ea7-ece1c842ec0b.png">

Is there a way to make this stop happening to the images I load in? Especially for the ones that are small?

**Comment by morevnaproject** [comment]
Hello! If you wish to move image layer, then please use "Animate Tool" -
![screenshot_002](https://user-images.githubusercontent.com/332868/40572845-dd33eb64-60e0-11e8-9890-0749f85b332f.png)

If you still prefer to use "Selection Tool" for editing position of your artwork, then you can use "Level" -> "Canvas Size" command dimensions of your image layer.
![screenshot_003](https://user-images.githubusercontent.com/332868/40572865-450e795c-60e1-11e8-8f28-c210ed87101c.png)
http://opentoonz.readthedocs.io/en/latest/drawing_animation_levels.html#changing-the-canvas-size
